# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  Glad_config = debug_win64
  NutLib_config = debug_win64
  Sandbox_config = debug_win64

else ifeq ($(config),release_win64)
  Glad_config = release_win64
  NutLib_config = release_win64
  Sandbox_config = release_win64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Glad NutLib Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Glad

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C NutLib/vendor/Glad -f Makefile config=$(Glad_config)
endif

NutLib: Glad
ifneq (,$(NutLib_config))
	@echo "==== Building NutLib ($(NutLib_config)) ===="
	@${MAKE} --no-print-directory -C NutLib -f Makefile config=$(NutLib_config)
endif

Sandbox: NutLib
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C NutLib/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C NutLib -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  release_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   NutLib"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"